# Site settings
title: Mathias Villerabel
description: AI Engineer & Data Scientist | Transforming data into actionable insights
author: Mathias Villerabel

# Theme settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Optional settings
logo: /assets/img/profilpic.jpg # Profile picture shown in sidebar
show_downloads: false

# Social links (optional - customize with your own)
github_username: MrEleden
linkedin_username: https://www.linkedin.com/in/mathias-villerabel-ba32b0146/
email: m.villerabel@gmail.com

# Google Analytics (optional)
# google_analytics: UA-XXXXXXXXX-X

# SEO settings
lang: en-US
